/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles/index'
import { Route as QuestionsAskRouteImport } from './routes/questions/ask'
import { Route as QuestionsIdRouteImport } from './routes/questions/$id'
import { Route as ProfilesSigninRouteImport } from './routes/profiles/signin'
import { Route as ProfilesIdRouteImport } from './routes/profiles/$id'
import { Route as ApiSignImageRouteImport } from './routes/api/sign-image'
import { Route as QuestionsEditIdRouteImport } from './routes/questions/edit.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsAskRoute = QuestionsAskRouteImport.update({
  id: '/questions/ask',
  path: '/questions/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIdRoute = QuestionsIdRouteImport.update({
  id: '/questions/$id',
  path: '/questions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesSigninRoute = ProfilesSigninRouteImport.update({
  id: '/profiles/signin',
  path: '/profiles/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignImageRoute = ApiSignImageRouteImport.update({
  id: '/api/sign-image',
  path: '/api/sign-image',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsEditIdRoute = QuestionsEditIdRouteImport.update({
  id: '/questions/edit/$id',
  path: '/questions/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sign-image': typeof ApiSignImageRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/profiles/signin': typeof ProfilesSigninRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/questions/ask': typeof QuestionsAskRoute
  '/profiles': typeof ProfilesIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/session': typeof SessionIndexRoute
  '/tags': typeof TagsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/edit/$id': typeof QuestionsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sign-image': typeof ApiSignImageRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/profiles/signin': typeof ProfilesSigninRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/questions/ask': typeof QuestionsAskRoute
  '/profiles': typeof ProfilesIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/session': typeof SessionIndexRoute
  '/tags': typeof TagsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/edit/$id': typeof QuestionsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/sign-image': typeof ApiSignImageRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/profiles/signin': typeof ProfilesSigninRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/questions/ask': typeof QuestionsAskRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/session/': typeof SessionIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/edit/$id': typeof QuestionsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/sign-image'
    | '/profiles/$id'
    | '/profiles/signin'
    | '/questions/$id'
    | '/questions/ask'
    | '/profiles'
    | '/questions'
    | '/session'
    | '/tags'
    | '/api/auth/$'
    | '/questions/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/sign-image'
    | '/profiles/$id'
    | '/profiles/signin'
    | '/questions/$id'
    | '/questions/ask'
    | '/profiles'
    | '/questions'
    | '/session'
    | '/tags'
    | '/api/auth/$'
    | '/questions/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/api/sign-image'
    | '/profiles/$id'
    | '/profiles/signin'
    | '/questions/$id'
    | '/questions/ask'
    | '/profiles/'
    | '/questions/'
    | '/session/'
    | '/tags/'
    | '/api/auth/$'
    | '/questions/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSignImageRoute: typeof ApiSignImageRoute
  ProfilesIdRoute: typeof ProfilesIdRoute
  ProfilesSigninRoute: typeof ProfilesSigninRoute
  QuestionsIdRoute: typeof QuestionsIdRoute
  QuestionsAskRoute: typeof QuestionsAskRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  SessionIndexRoute: typeof SessionIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  QuestionsEditIdRoute: typeof QuestionsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/ask': {
      id: '/questions/ask'
      path: '/questions/ask'
      fullPath: '/questions/ask'
      preLoaderRoute: typeof QuestionsAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$id': {
      id: '/questions/$id'
      path: '/questions/$id'
      fullPath: '/questions/$id'
      preLoaderRoute: typeof QuestionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/signin': {
      id: '/profiles/signin'
      path: '/profiles/signin'
      fullPath: '/profiles/signin'
      preLoaderRoute: typeof ProfilesSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id': {
      id: '/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sign-image': {
      id: '/api/sign-image'
      path: '/api/sign-image'
      fullPath: '/api/sign-image'
      preLoaderRoute: typeof ApiSignImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/edit/$id': {
      id: '/questions/edit/$id'
      path: '/questions/edit/$id'
      fullPath: '/questions/edit/$id'
      preLoaderRoute: typeof QuestionsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSignImageRoute: ApiSignImageRoute,
  ProfilesIdRoute: ProfilesIdRoute,
  ProfilesSigninRoute: ProfilesSigninRoute,
  QuestionsIdRoute: QuestionsIdRoute,
  QuestionsAskRoute: QuestionsAskRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  SessionIndexRoute: SessionIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  QuestionsEditIdRoute: QuestionsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
