api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--messaging
        value: amqp://guest:{{ uriEncode (securedParameter "messaging_password" )}}@messaging:5672
      - name: messaging-password
        value: '{{ securedParameter "messaging_password" }}'
      - name: typesense-api-key
        value: '{{ securedParameter "typesense_api_key" }}'
  template:
    containers:
      - image: {{ .Image }}
        name: search-svc
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: MESSAGING_HOST
            value: messaging
          - name: MESSAGING_PORT
            value: "5672"
          - name: MESSAGING_URI
            value: amqp://guest:{{ uriEncode (securedParameter "messaging_password" )}}@messaging:5672
          - name: MESSAGING_USERNAME
            value: guest
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: TYPESENSE_TYPESENSE
            value: http://typesense.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__typesense__typesense__0
            value: http://typesense.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: ConnectionStrings__messaging
            secretRef: connectionstrings--messaging
          - name: MESSAGING_PASSWORD
            secretRef: messaging-password
          - name: typesense-api-key
            secretRef: typesense-api-key
    scale:
      minReplicas: 1
tags:
  azd-service-name: search-svc
  aspire-resource-name: search-svc
